//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossroads.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentFlags = new HashSet<CommentFlag>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Flags { get; set; }
        public int AnswerId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
    
        public virtual Answer Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentFlag> CommentFlags { get; set; }
        public virtual User User { get; set; }
    }
}
