//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossroads.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrossroadsDbContext : DbContext
    {
        public CrossroadsDbContext()
            : base("name=Crossroads")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerFlag> AnswerFlags { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AnswerVote> AnswerVotes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CommentFlag> CommentFlags { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<MusicGenre> MusicGenres { get; set; }
        public virtual DbSet<ProfileComment> ProfileComments { get; set; }
        public virtual DbSet<ProfileInterest> ProfileInterests { get; set; }
        public virtual DbSet<ProfileMessage> ProfileMessages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TopicFlag> TopicFlags { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TopicVote> TopicVotes { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
